id: I699EB97F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T22:20:56+00:00'
last_modified: '2022-06-08T12:17:53.576794+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11703
  title: རྒྱུད་བཅུ་བདུན། （ཨ་འཛོམ་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    00FB:
      image_group_id: I1KG11710
      title: ''
      total_pages: 390
      order: 1
      base_file: 00FB.txt
    6DFB:
      image_group_id: I1KG11711
      title: ''
      total_pages: 580
      order: 2
      base_file: 6DFB.txt
    DBE1:
      image_group_id: I1KG11712
      title: ''
      total_pages: 582
      order: 3
      base_file: DBE1.txt
    75E7:
      image_group_id: I1KG11713
      title: ''
      total_pages: 438
      order: 4
      base_file: 75E7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
