id: I699EB97F
legacy_id: P009617
ocr_import_info:
  bdrc_scan_id: W1KG11703
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T22:17:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:01:14.967604+00:00'
last_modified: 2022-08-31 11:02:27.507199
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11703
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11703
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་བཅུ་བདུན། （ཨ་འཛོམ་པར་མ།）
statistics:
  ocr_word_mean_confidence_index: 0.5892777304877617
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1KG11713:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11713
      total_pages: 438
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG11713.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5727395888808519
    legacy_id: v004
  I1KG11711:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11711
      total_pages: 580
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG11711.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.5976691236898084
    legacy_id: v002
  I1KG11712:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11712
      total_pages: 582
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG11712.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5833481850315645
    legacy_id: v003
  I1KG11710:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11710
      total_pages: 390
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11710.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6057481345908929
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
